/**
 * Sync contract — collection lists shared between web (`syncService.ts`)
 * and iOS (`SyncService.swift`).
 *
 * Historically these lists were hand-mirrored between the two platforms
 * and only verified by manual audit (workstream C4 / issue #261). This
 * file is now the single source of truth:
 *
 *  - **Web** imports these arrays directly (`apps/web/src/firebase/syncService.ts`).
 *  - **iOS** cannot import TypeScript, so it asserts equality against a
 *    generated JSON fixture instead — see
 *    `packages/shared/tests/fixtures/syncContract.json` (generated by
 *    `pnpm --filter @oybc/shared run gen:sync-contract`, enforced in sync
 *    by `packages/shared/tests/constants/syncContract.test.ts`) and
 *    `apps/ios/OYBCTests/SyncContractTests.swift`, which loads that same
 *    JSON file (bundled as a test resource) and compares it against
 *    `SyncService.swift`'s `syncableCollections` / `userScopedCollections`
 *    / `legacyPullSkipCollections`.
 *
 * Editing this file WITHOUT regenerating the fixture makes the shared
 * Jest test fail loudly (rather than the two platforms silently drifting
 * apart again).
 */

/**
 * All Firestore subcollection names under `users/{userId}/` that
 * participate in sync (push and/or pull). This is the full syncable set —
 * see `LEGACY_PULL_SKIP_COLLECTIONS` for the subset the pull path skips.
 *
 * Order matches the historical web `SYNCABLE_COLLECTIONS` list. Neither
 * consumer depends on iteration order for correctness (the pull loop
 * processes each collection independently), but the order is preserved
 * here to keep git history/diffs against that original list minimal.
 *
 * The three Compound-Tasks-Unification collections (`taskSteps`,
 * `compositeTasks`, `compositeNodes`) were removed from this list once
 * their tables were dropped and every device had drained its migration
 * tombstones — see CLAUDE.md's "Task model" section for the history.
 *
 * Consumers: web `SYNCABLE_COLLECTIONS` in `syncService.ts`; iOS
 * `syncableCollections` (the `firestoreName` half of each tuple) in
 * `SyncService.swift`.
 */
export const SYNC_COLLECTIONS = [
  'boards',
  'tasks',
  'boardTasks',
  'compoundChildren',
  'recurringBoardTemplates',
  'defaultPools',
  // Windowed Completion (docs/WINDOWED_COMPLETION.md §Sync). Per-row LWW +
  // soft-delete tombstones like compoundChildren. Carries a `userId` field, so
  // it also joins USER_SCOPED_SYNC_COLLECTIONS below.
  'taskEvents',
  // Task Pools + Recurring Boards Rework (P1, docs/POOLS_RECURRING.md
  // §Data model). Standard per-row LWW + tombstones, both carry `userId`
  // → also join USER_SCOPED_SYNC_COLLECTIONS below.
  'pools',
  'coreBoardDefaults',
] as const;

/** Union of the literal collection-name strings in `SYNC_COLLECTIONS`. */
export type SyncCollection = (typeof SYNC_COLLECTIONS)[number];

/**
 * Subset of `SYNC_COLLECTIONS` whose Firestore documents carry a
 * top-level `userId` field. The pull path on both platforms rejects any
 * document whose `userId` doesn't match the authenticated user — a
 * defense-in-depth check against a compromised peer that writes into its
 * own path with a spoofed `userId` and hopes a future cross-user share
 * path surfaces it.
 *
 * Consumers: web `USER_SCOPED_COLLECTIONS` in `syncService.ts`; iOS
 * `userScopedCollections` in `SyncService.swift`.
 */
export const USER_SCOPED_SYNC_COLLECTIONS = [
  'boards',
  'tasks',
  'recurringBoardTemplates',
  'defaultPools',
  // TaskEvent rows carry a top-level `userId` (docs/WINDOWED_COMPLETION.md
  // §New entity) → the pull path enforces the owner-match check.
  'taskEvents',
  // P1 — Pool and CoreBoardDefault rows both carry a top-level `userId`.
  'pools',
  'coreBoardDefaults',
] as const satisfies readonly SyncCollection[];

/**
 * Subset of `SYNC_COLLECTIONS` that the **pull** path must skip even
 * though they remain in the full syncable list so the **push** path can
 * drain their DELETE tombstones. Pulling a document into a retired
 * collection would resurrect a row that no live code reads (or, where the
 * table has been dropped, attempt to upsert into a nonexistent table).
 *
 * `defaultPools` is the current member (the Compound-Tasks-Unification
 * collections that used the same pattern were fully removed from the
 * contract once their tables were dropped). It joined this list in P1
 * (Task Pools + Recurring Boards Rework, docs/POOLS_RECURRING.md
 * §Migration): first-launch backfill migrates every `DefaultPool` row
 * into a `Pool` + `CoreBoardDefault` pair and soft-deletes the
 * `DefaultPool` row. It stays in `SYNC_COLLECTIONS` so the push path can
 * drain those DELETE tombstones, but the pull path must not resurrect a
 * `DefaultPool` row a peer already migrated away.
 *
 * Consumers: web `LEGACY_PULL_SKIP_COLLECTIONS` in `syncService.ts`; iOS
 * `legacyPullSkipCollections` in `SyncService.swift`.
 */
export const LEGACY_PULL_SKIP_COLLECTIONS = [
  'defaultPools',
] as const satisfies readonly SyncCollection[];
