/**
 * Sync contract — collection lists shared between web (`syncService.ts`)
 * and iOS (`SyncService.swift`).
 *
 * Historically these lists were hand-mirrored between the two platforms
 * and only verified by manual audit (workstream C4 / issue #261). This
 * file is now the single source of truth:
 *
 *  - **Web** imports these arrays directly (`apps/web/src/firebase/syncService.ts`).
 *  - **iOS** cannot import TypeScript, so it asserts equality against a
 *    generated JSON fixture instead — see
 *    `packages/shared/tests/fixtures/syncContract.json` (generated by
 *    `pnpm --filter @oybc/shared run gen:sync-contract`, enforced in sync
 *    by `packages/shared/tests/constants/syncContract.test.ts`) and
 *    `apps/ios/OYBCTests/SyncContractTests.swift`, which loads that same
 *    JSON file (bundled as a test resource) and compares it against
 *    `SyncService.swift`'s `syncableCollections` / `userScopedCollections`
 *    / `legacyPullSkipCollections`.
 *
 * Editing this file WITHOUT regenerating the fixture makes the shared
 * Jest test fail loudly (rather than the two platforms silently drifting
 * apart again).
 */

/**
 * All Firestore subcollection names under `users/{userId}/` that
 * participate in sync (push and/or pull). This is the full syncable set —
 * see `LEGACY_PULL_SKIP_COLLECTIONS` for the subset the pull path skips.
 *
 * Order matches the historical web `SYNCABLE_COLLECTIONS` list. Neither
 * consumer depends on iteration order for correctness (the pull loop
 * processes each collection independently), but the order is preserved
 * here to keep git history/diffs against that original list minimal.
 *
 * Includes three collections retired at the data-model level in the
 * Compound Tasks Unification (`taskSteps`, `compositeTasks`,
 * `compositeNodes` — replaced by `compound_children` / `compoundChildren`).
 * They stay in this list so the **push** path can drain DELETE
 * tombstones produced by the migration cleanup; see
 * `LEGACY_PULL_SKIP_COLLECTIONS` for why the **pull** path must not read
 * from them. See CLAUDE.md's "Task model — Compound Tasks Unification"
 * section for the full migration story.
 *
 * Consumers: web `SYNCABLE_COLLECTIONS` in `syncService.ts`; iOS
 * `syncableCollections` (the `firestoreName` half of each tuple) in
 * `SyncService.swift`.
 */
export const SYNC_COLLECTIONS = [
  'boards',
  'tasks',
  'taskSteps',
  'boardTasks',
  'compositeTasks',
  'compositeNodes',
  'compoundChildren',
  'recurringBoardTemplates',
  'defaultPools',
] as const;

/** Union of the literal collection-name strings in `SYNC_COLLECTIONS`. */
export type SyncCollection = (typeof SYNC_COLLECTIONS)[number];

/**
 * Subset of `SYNC_COLLECTIONS` whose Firestore documents carry a
 * top-level `userId` field. The pull path on both platforms rejects any
 * document whose `userId` doesn't match the authenticated user — a
 * defense-in-depth check against a compromised peer that writes into its
 * own path with a spoofed `userId` and hopes a future cross-user share
 * path surfaces it.
 *
 * Consumers: web `USER_SCOPED_COLLECTIONS` in `syncService.ts`; iOS
 * `userScopedCollections` in `SyncService.swift`.
 */
export const USER_SCOPED_SYNC_COLLECTIONS = [
  'boards',
  'tasks',
  'compositeTasks',
  'recurringBoardTemplates',
  'defaultPools',
] as const satisfies readonly SyncCollection[];

/**
 * Subset of `SYNC_COLLECTIONS` that the **pull** path must skip even
 * though they remain in the full syncable list so the **push** path can
 * drain their DELETE tombstones. Their underlying GRDB/Dexie tables were
 * dropped at the model level in the Compound Tasks Unification — pulling
 * a document into a retired collection would either resurrect a legacy
 * row that no live code reads, or (on iOS) attempt to upsert into a
 * dropped table.
 *
 * Consumers: web `LEGACY_PULL_SKIP_COLLECTIONS` in `syncService.ts`; iOS
 * `legacyPullSkipCollections` in `SyncService.swift`.
 */
export const LEGACY_PULL_SKIP_COLLECTIONS = [
  'taskSteps',
  'compositeTasks',
  'compositeNodes',
] as const satisfies readonly SyncCollection[];
