import * as fs from 'fs';
import * as path from 'path';
import { buildSharedCounterGroups } from '../../src/algorithms/sharedCounterGroups';
import { BoardStatus, TaskType, Timeframe, CenterSquareType } from '../../src/constants/enums';
import type { Task } from '../../src/types/task';
import type { Board } from '../../src/types/board';
import type { BoardTask } from '../../src/types/boardTask';

/**
 * C1 (issue #267): fully fixture-driven from
 * `tests/fixtures/sharedCounterGroupsVectors.json` — the SAME file
 * `apps/ios/OYBCTests/SharedCounterGroupsVectorTests.swift` runs through the
 * Swift mirror `buildSharedCounterGroups`. Pre-C1: 11 `it` blocks. Post-C1:
 * 11 fixture vectors — a 1:1 mapping, no case dropped. Every vector's
 * `expected` is the FULL groups array (not just the fields the original
 * assertions checked), generated by running the real TS function once
 * during fixture authoring — so this file's assertions are a strict
 * superset of the pre-C1 coverage.
 */

const FIXTURE_PATH = path.join(__dirname, '../fixtures/sharedCounterGroupsVectors.json');
const TS = '2026-02-01T12:00:00.000Z';

interface MiniTask {
  id: string;
  title: string;
  currentCount: number | null;
  maxCount: number | null;
  sharedCounterId: string | null;
  baseline: number | null;
  isDeleted: boolean;
}

interface MiniBoard {
  id: string;
  name: string;
  status: string;
  isDeleted: boolean;
}

interface MiniBoardTask {
  taskId: string;
  boardId: string;
}

interface MiniMemberTask {
  taskId: string;
  isSource: boolean;
  boardId: string | null;
  boardName: string | null;
  goal: number;
  logged: number;
  met: boolean;
  over: number;
  isActive: boolean;
}

interface MiniGroup {
  counterId: string;
  name: string;
  lifetime: number;
  taskCount: number;
  boardCount: number;
  activeTaskCount: number;
  tasks: MiniMemberTask[];
}

interface Vector {
  name: string;
  tasks: MiniTask[];
  boards: MiniBoard[];
  boardTasks: MiniBoardTask[];
  expected: MiniGroup[];
}

interface Fixture {
  vectors: Vector[];
}

const fixture: Fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));

function toTask(m: MiniTask): Task {
  return {
    id: m.id,
    userId: 'u1',
    title: m.title,
    type: TaskType.COUNTING,
    action: 'Do',
    unit: 'reps',
    maxCount: m.maxCount ?? undefined,
    currentCount: m.currentCount ?? undefined,
    sharedCounterId: m.sharedCounterId,
    baseline: m.baseline,
    isCompleted: false,
    totalCompletions: 0,
    totalInstances: 0,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
    isDeleted: m.isDeleted,
  };
}

function toBoard(m: MiniBoard): Board {
  return {
    id: m.id,
    userId: 'u1',
    name: m.name,
    status: m.status as BoardStatus,
    boardSize: 5,
    timeframe: Timeframe.WEEKLY,
    startDate: TS,
    endDate: '2026-02-07T12:00:00.000Z',
    centerSquareType: CenterSquareType.FREE,
    isRandomized: false,
    totalTasks: 25,
    completedTasks: 0,
    linesCompleted: 0,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
    isDeleted: m.isDeleted,
  };
}

function toBoardTask(m: MiniBoardTask): BoardTask {
  return {
    id: `bt-${m.taskId}-${m.boardId}`,
    boardId: m.boardId,
    taskId: m.taskId,
    row: 0,
    col: 0,
    isCenter: false,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
  };
}

describe('buildSharedCounterGroups (fixture-driven, tests/fixtures/sharedCounterGroupsVectors.json)', () => {
  it('fixture is non-empty', () => {
    expect(fixture.vectors.length).toBeGreaterThan(0);
  });

  for (const v of fixture.vectors) {
    it(v.name, () => {
      const groups = buildSharedCounterGroups({
        tasks: v.tasks.map(toTask),
        boards: v.boards.map(toBoard),
        boardTasks: v.boardTasks.map(toBoardTask),
      });

      expect(groups).toHaveLength(v.expected.length);
      groups.forEach((g, i) => {
        const exp = v.expected[i];
        expect(g.counterId).toBe(exp.counterId);
        expect(g.name).toBe(exp.name);
        expect(g.lifetime).toBe(exp.lifetime);
        expect(g.taskCount).toBe(exp.taskCount);
        expect(g.boardCount).toBe(exp.boardCount);
        expect(g.activeTaskCount).toBe(exp.activeTaskCount);
        expect(g.tasks).toHaveLength(exp.tasks.length);
        g.tasks.forEach((m, j) => {
          const expMember = exp.tasks[j];
          expect(m.taskId).toBe(expMember.taskId);
          expect(m.isSource).toBe(expMember.isSource);
          expect(m.boardId).toBe(expMember.boardId);
          expect(m.boardName).toBe(expMember.boardName);
          expect(m.goal).toBe(expMember.goal);
          expect(m.logged).toBe(expMember.logged);
          expect(m.met).toBe(expMember.met);
          expect(m.over).toBe(expMember.over);
          expect(m.isActive).toBe(expMember.isActive);
        });
      });
    });
  }
});
