import * as fs from 'fs';
import * as path from 'path';
import {
  buildSharedCounterGroups,
  sharedCounterRootIds,
} from '../../src/algorithms/sharedCounterGroups';
import { BoardStatus, TaskType, Timeframe, CenterSquareType } from '../../src/constants/enums';
import type { Task } from '../../src/types/task';
import type { Board } from '../../src/types/board';
import type { BoardTask } from '../../src/types/boardTask';
import type { TaskEvent } from '../../src/types/taskEvent';

/**
 * C1 (issue #267): fully fixture-driven from
 * `tests/fixtures/sharedCounterGroupsVectors.json` — the SAME file
 * `apps/ios/OYBCTests/SharedCounterGroupsVectorTests.swift` runs through the
 * Swift mirror `buildSharedCounterGroups`. Pre-C1: 11 `it` blocks. Post-C1:
 * 11 fixture vectors — a 1:1 mapping, no case dropped. Every vector's
 * `expected` is the FULL groups array (not just the fields the original
 * assertions checked), generated by running the real TS function once
 * during fixture authoring — so this file's assertions are a strict
 * superset of the pre-C1 coverage.
 */

const FIXTURE_PATH = path.join(__dirname, '../fixtures/sharedCounterGroupsVectors.json');
const TS = '2026-02-01T12:00:00.000Z';

interface MiniTask {
  id: string;
  title: string;
  currentCount: number | null;
  maxCount: number | null;
  sharedCounterId: string | null;
  baseline: number | null;
  isDeleted: boolean;
  /** P5 hub-born-counter flag. Optional — absent/false on the core 11 vectors. */
  isCounter?: boolean;
  /** Window-stamped derived member fields (optional; Task 3 vectors). */
  startDate?: string | null;
  endDate?: string | null;
  createdInWizard?: boolean;
}

interface MiniBoard {
  id: string;
  name: string;
  status: string;
  isDeleted: boolean;
  /** Optional — a sealed board's seal instant. */
  sealedAt?: string;
}

interface MiniBoardTask {
  taskId: string;
  boardId: string;
  isDeleted?: boolean;
}

interface MiniMemberTask {
  taskId: string;
  isSource: boolean;
  boardId: string | null;
  boardName: string | null;
  goal: number;
  logged: number;
  met: boolean;
  over: number;
  isActive: boolean;
}

interface MiniGroup {
  counterId: string;
  name: string;
  lifetime: number;
  taskCount: number;
  boardCount: number;
  activeTaskCount: number;
  tasks: MiniMemberTask[];
}

interface Vector {
  name: string;
  tasks: MiniTask[];
  boards: MiniBoard[];
  boardTasks: MiniBoardTask[];
  /** Optional — root id → increment events; passed through as `eventsByTaskId`. */
  eventsByTaskId?: Record<string, Array<{ id: string; kind: 'increment'; delta: number; occurredAt: string; isDeleted: boolean }>>;
  expected: MiniGroup[];
}

interface Fixture {
  vectors: Vector[];
}

const fixture: Fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));

function toTask(m: MiniTask): Task {
  return {
    id: m.id,
    userId: 'u1',
    title: m.title,
    type: TaskType.COUNTING,
    // R1 (pair-derived counter names): intentionally NOT set here. These
    // fixture vectors predate pair-derived naming and were authored to
    // assert on `title`; leaving action/unit unset means
    // `formatCounterName(undefined, undefined) === ''`, so
    // `buildSharedCounterGroups`'s `name` falls back to the stored `title`
    // (docs: the pair-can't-produce-a-name fallback) — every vector's
    // `expected.name` stays exactly what it was pre-R1. Pair-derivation
    // itself is covered by tests/algorithms/counterName.test.ts and the
    // "pair-derived counter names (R1)" describe block below.
    maxCount: m.maxCount ?? undefined,
    currentCount: m.currentCount ?? undefined,
    sharedCounterId: m.sharedCounterId,
    baseline: m.baseline,
    isCompleted: false,
    totalCompletions: 0,
    totalInstances: 0,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
    isDeleted: m.isDeleted,
    isCounter: m.isCounter,
    startDate: m.startDate ?? undefined,
    endDate: m.endDate ?? undefined,
    createdInWizard: m.createdInWizard,
  };
}

function toBoard(m: MiniBoard): Board {
  return {
    id: m.id,
    userId: 'u1',
    name: m.name,
    status: m.status as BoardStatus,
    boardSize: 5,
    timeframe: Timeframe.WEEKLY,
    startDate: TS,
    endDate: '2026-02-07T12:00:00.000Z',
    centerSquareType: CenterSquareType.FREE,
    isRandomized: false,
    totalTasks: 25,
    completedTasks: 0,
    linesCompleted: 0,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
    isDeleted: m.isDeleted,
    sealedAt: m.sealedAt,
  };
}

function toVectorEvents(v: Vector): Record<string, TaskEvent[]> | undefined {
  if (!v.eventsByTaskId) return undefined;
  const out: Record<string, TaskEvent[]> = {};
  for (const [taskId, evs] of Object.entries(v.eventsByTaskId)) {
    out[taskId] = evs.map((e) => ({
      ...e,
      userId: 'u1',
      taskId,
      createdAt: TS,
      updatedAt: TS,
      version: 1,
    }));
  }
  return out;
}

function toBoardTask(m: MiniBoardTask): BoardTask {
  return {
    id: `bt-${m.taskId}-${m.boardId}`,
    boardId: m.boardId,
    taskId: m.taskId,
    row: 0,
    col: 0,
    isCenter: false,
    createdAt: TS,
    updatedAt: TS,
    version: 1,
    isDeleted: m.isDeleted ?? false,
  };
}

/**
 * P5 — hub-born counters. NOT added to the shared fixture-vector JSON above:
 * that file is consumed by BOTH this TS test and
 * `apps/ios/OYBCTests/SharedCounterGroupsVectorTests.swift` against the
 * Swift mirror, which doesn't have `isCounter` support yet (Swift port is
 * PR-2). These cases reuse the same `toTask`/`toBoard`/`toBoardTask`
 * fixture builders as the vector-driven suite above, spreading `isCounter`
 * onto the `MiniTask`-built `Task` since `MiniTask` predates the P5 flag.
 */
describe('sharedCounterRootIds — the extracted family-root test', () => {
  const counting = (id: string, over: Partial<Task> = {}): Task => ({
    ...toTask({
      id,
      title: `Task ${id}`,
      currentCount: 0,
      maxCount: 10,
      sharedCounterId: null,
      baseline: null,
      isDeleted: false,
    }),
    ...over,
  });

  it('does NOT name a link target that is absent, deleted, or not a counting task', () => {
    const memberOfMissing = counting('member-of-missing', { sharedCounterId: 'never-synced' });
    const deletedRoot = counting('deleted-root', { isDeleted: true });
    const memberOfDeleted = counting('member-of-deleted', { sharedCounterId: 'deleted-root' });
    const normalRoot: Task = { ...counting('normal-root'), type: TaskType.NORMAL };
    const memberOfNormal = counting('member-of-normal', { sharedCounterId: 'normal-root' });

    const roots = sharedCounterRootIds([
      memberOfMissing,
      deletedRoot,
      memberOfDeleted,
      normalRoot,
      memberOfNormal,
    ]);

    // A dangling link must not conjure a family whose hub page would be empty.
    expect(roots).toEqual(new Set());
  });

  it('names a root by link, a hub-born root by flag, and neither a plain counter nor a deleted member\u2019s target', () => {
    const linkRoot = counting('link-root');
    const member = counting('member', { sharedCounterId: 'link-root' });
    const hubBorn = counting('hub-born', { isCounter: true });
    const plain = counting('plain'); // a standalone counter heads no family
    const ghostTarget = counting('ghost-target');
    const deletedMember = counting('deleted-member', {
      sharedCounterId: 'ghost-target',
      isDeleted: true,
    });

    const roots = sharedCounterRootIds([
      linkRoot,
      member,
      hubBorn,
      plain,
      ghostTarget,
      deletedMember,
    ]);

    expect(roots).toEqual(new Set(['link-root', 'hub-born']));
  });

  it('agrees with the hub in BOTH directions — the helper and the groups name the same set', () => {
    const linkRoot = counting('link-root');
    const member = counting('member', { sharedCounterId: 'link-root' });
    const hubBorn = counting('hub-born', { isCounter: true });
    const plain = counting('plain');
    // Orphan links of every flavour: none may head a group, none may be a root.
    const memberOfMissing = counting('member-of-missing', { sharedCounterId: 'never-synced' });
    const deletedRoot = counting('deleted-root', { isDeleted: true });
    const memberOfDeleted = counting('member-of-deleted', { sharedCounterId: 'deleted-root' });
    const normalRoot: Task = { ...counting('normal-root'), type: TaskType.NORMAL };
    const memberOfNormal = counting('member-of-normal', { sharedCounterId: 'normal-root' });

    const tasks = [
      linkRoot,
      member,
      hubBorn,
      plain,
      memberOfMissing,
      deletedRoot,
      memberOfDeleted,
      normalRoot,
      memberOfNormal,
    ];
    const groups = buildSharedCounterGroups({ tasks, boardTasks: [], boards: [] });
    const roots = sharedCounterRootIds(tasks);

    expect(groups.map((g) => g.counterId).sort()).toEqual(['hub-born', 'link-root']);
    // Both directions: no group without a root, and no root without a group.
    // `computeBrowsableTasks` hides a member on the strength of this set, so a
    // one-way check would let a root exist that the hub never renders.
    expect(new Set(groups.map((g) => g.counterId))).toEqual(roots);
  });
});

describe('hub-born counters (P5)', () => {
  it('a flagged zero-link source becomes a single-member group', () => {
    const source = {
      ...toTask({
        id: 'c1',
        title: 'Counter c1',
        currentCount: 500,
        maxCount: null,
        sharedCounterId: null,
        baseline: null,
        isDeleted: false,
      }),
      isCounter: true,
    };

    const groups = buildSharedCounterGroups({
      tasks: [source],
      boards: [],
      boardTasks: [],
    });

    expect(groups).toHaveLength(1);
    const [group] = groups;
    expect(group.counterId).toBe('c1');
    expect(group.lifetime).toBe(500);
    expect(group.taskCount).toBe(1);
    expect(group.boardCount).toBe(0);
    expect(group.tasks).toHaveLength(1);
    expect(group.tasks[0].isSource).toBe(true);
    expect(group.tasks[0].goal).toBe(0);
    expect(group.tasks[0].met).toBe(false);
  });

  it('a flagged source WITH links produces one group, not two', () => {
    const source = {
      ...toTask({
        id: 'src',
        title: 'Counter src',
        currentCount: 200,
        maxCount: null,
        sharedCounterId: null,
        baseline: null,
        isDeleted: false,
      }),
      isCounter: true,
    };
    const linked = toTask({
      id: 'der',
      title: 'Counter der',
      currentCount: null,
      maxCount: 50,
      sharedCounterId: 'src',
      baseline: 0,
      isDeleted: false,
    });

    const groups = buildSharedCounterGroups({
      tasks: [source, linked],
      boards: [],
      boardTasks: [],
    });

    expect(groups).toHaveLength(1);
    expect(groups[0].counterId).toBe('src');
    expect(groups[0].taskCount).toBe(2);
  });

  it('an unflagged standalone counting task still produces no group', () => {
    const standalone = toTask({
      id: 'a',
      title: 'Counter a',
      currentCount: 5,
      maxCount: null,
      sharedCounterId: null,
      baseline: null,
      isDeleted: false,
    });

    const groups = buildSharedCounterGroups({
      tasks: [standalone],
      boards: [],
      boardTasks: [],
    });

    expect(groups).toHaveLength(0);
  });

  it('a flagged but DERIVED task is ignored (malformed row)', () => {
    // Malformed: isCounter + sharedCounterId set together — Zod rejects this
    // combination at input-validation time, but the pure read-model is
    // defensive against a row that slipped through anyway.
    const malformed = {
      ...toTask({
        id: 'mal',
        title: 'Counter mal',
        currentCount: 10,
        maxCount: null,
        sharedCounterId: 'missing-source',
        baseline: 0,
        isDeleted: false,
      }),
      isCounter: true,
    };

    const groups = buildSharedCounterGroups({
      tasks: [malformed],
      boards: [],
      boardTasks: [],
    });

    expect(groups.find((g) => g.counterId === 'mal')).toBeUndefined();
    expect(groups).toHaveLength(0);
  });
});

describe('pair-derived counter names (R1)', () => {
  it("derives the group name from the source task's action+unit pair, eliding a default Do", () => {
    const source = {
      ...toTask({
        id: 'src',
        title: 'Fallback title (should not be used)',
        currentCount: 40,
        maxCount: null,
        sharedCounterId: null,
        baseline: null,
        isDeleted: false,
      }),
      action: 'Do',
      unit: 'push-ups',
      isCounter: true,
    };

    const groups = buildSharedCounterGroups({ tasks: [source], boards: [], boardTasks: [] });

    expect(groups).toHaveLength(1);
    expect(groups[0].name).toBe('Push-ups');
  });

  it('keeps a non-Do verb in the derived name', () => {
    const source = {
      ...toTask({
        id: 'src',
        title: 'Fallback title (should not be used)',
        currentCount: 10,
        maxCount: null,
        sharedCounterId: null,
        baseline: null,
        isDeleted: false,
      }),
      action: 'Run',
      unit: 'miles',
      isCounter: true,
    };

    const groups = buildSharedCounterGroups({ tasks: [source], boards: [], boardTasks: [] });

    expect(groups).toHaveLength(1);
    expect(groups[0].name).toBe('Run miles');
  });

  it('falls back to the stored title when the pair cannot produce a name', () => {
    const source = {
      ...toTask({
        id: 'src2',
        title: 'Stored Title',
        currentCount: 10,
        maxCount: null,
        sharedCounterId: null,
        baseline: null,
        isDeleted: false,
      }),
      isCounter: true,
    };

    const groups = buildSharedCounterGroups({ tasks: [source], boards: [], boardTasks: [] });

    expect(groups).toHaveLength(1);
    expect(groups[0].name).toBe('Stored Title');
  });
});

// Board-integrity PR-1 (docs/BOARD_INTEGRITY.md) — `pickPrimaryBoard` (the
// internal board-resolution helper) must never surface a board through a
// TOMBSTONED placement, or a member row would show a "primary board" it's
// no longer actually placed on.
describe('primary-board resolution excludes tombstoned placements', () => {
  it('a member whose only placement is tombstoned resolves to no board (not the dead one)', () => {
    const source = toTask({
      id: 'src',
      title: 'Source',
      currentCount: 10,
      maxCount: null,
      sharedCounterId: null,
      baseline: null,
      isDeleted: false,
      isCounter: true,
    });
    const board = toBoard({ id: 'board-1', name: 'Board One', status: BoardStatus.ACTIVE, isDeleted: false });

    const groups = buildSharedCounterGroups({
      tasks: [source],
      boards: [board],
      boardTasks: [{ taskId: 'src', boardId: 'board-1', isDeleted: true }].map(toBoardTask),
    });

    expect(groups).toHaveLength(1);
    expect(groups[0].boardCount).toBe(0);
    expect(groups[0].tasks[0].boardId).toBeNull();
    expect(groups[0].tasks[0].isActive).toBe(false);
  });

  it('a member with both a tombstoned and a live placement resolves to the live board', () => {
    const source = toTask({
      id: 'src',
      title: 'Source',
      currentCount: 10,
      maxCount: null,
      sharedCounterId: null,
      baseline: null,
      isDeleted: false,
      isCounter: true,
    });
    const deadBoard = toBoard({ id: 'board-dead', name: 'Dead', status: BoardStatus.ACTIVE, isDeleted: false });
    const liveBoard = toBoard({ id: 'board-live', name: 'Live', status: BoardStatus.ACTIVE, isDeleted: false });

    const groups = buildSharedCounterGroups({
      tasks: [source],
      boards: [deadBoard, liveBoard],
      boardTasks: [
        { taskId: 'src', boardId: 'board-dead', isDeleted: true },
        { taskId: 'src', boardId: 'board-live' },
      ].map(toBoardTask),
    });

    expect(groups).toHaveLength(1);
    expect(groups[0].tasks[0].boardId).toBe('board-live');
  });
});

describe('buildSharedCounterGroups (fixture-driven, tests/fixtures/sharedCounterGroupsVectors.json)', () => {
  it('fixture is non-empty', () => {
    expect(fixture.vectors.length).toBeGreaterThan(0);
  });

  for (const v of fixture.vectors) {
    it(v.name, () => {
      const groups = buildSharedCounterGroups({
        tasks: v.tasks.map(toTask),
        boards: v.boards.map(toBoard),
        boardTasks: v.boardTasks.map(toBoardTask),
        eventsByTaskId: toVectorEvents(v),
      });

      expect(groups).toHaveLength(v.expected.length);
      groups.forEach((g, i) => {
        const exp = v.expected[i];
        expect(g.counterId).toBe(exp.counterId);
        expect(g.name).toBe(exp.name);
        expect(g.lifetime).toBe(exp.lifetime);
        expect(g.taskCount).toBe(exp.taskCount);
        expect(g.boardCount).toBe(exp.boardCount);
        expect(g.activeTaskCount).toBe(exp.activeTaskCount);
        expect(g.tasks).toHaveLength(exp.tasks.length);
        g.tasks.forEach((m, j) => {
          const expMember = exp.tasks[j];
          expect(m.taskId).toBe(expMember.taskId);
          expect(m.isSource).toBe(expMember.isSource);
          expect(m.boardId).toBe(expMember.boardId);
          expect(m.boardName).toBe(expMember.boardName);
          expect(m.goal).toBe(expMember.goal);
          expect(m.logged).toBe(expMember.logged);
          expect(m.met).toBe(expMember.met);
          expect(m.over).toBe(expMember.over);
          expect(m.isActive).toBe(expMember.isActive);
        });
      });
    });
  }
});
