import * as fs from 'fs';
import * as path from 'path';
import { placeBoard } from '../src/placement';
import { CenterSquareType } from '../src/constants';

/**
 * Board-integrity PR-5 (issue #362), Item 1: `placeBoard` / `fisherYatesShuffle`
 * / `centerSquare` were the last unpinned kernels in the audit — every prior
 * placement assertion in `placement.test.ts` (and its Swift twin,
 * `apps/ios/OYBCTests/BoardPlacementTests.swift`) was a HAND-COPIED `expected`
 * array, so a silent behavioral drift between TS and Swift (or a regression
 * within one platform) could slip through if both sides' hand-copies drifted
 * together.
 *
 * `tests/fixtures/placementVectors.json` pins the seeded-LCG cases from
 * `placement.test.ts` as ONE canonical, cross-platform-shared source: this
 * file drives `placeBoard` from it directly, and the SAME file (synced via
 * `pnpm --filter @oybc/shared run gen:sync-fixtures` to
 * `apps/ios/OYBCTests/Fixtures/placementVectors.json`) drives the Swift
 * vector test. Both suites passing is the proof the two implementations
 * agree — not just that each hand-copy matches itself.
 *
 * Every `expected` value here was generated by running the CURRENT
 * `placeBoard` implementation (see PR description / commit for the
 * generation script) and cross-checked against the pre-existing hand-copied
 * arrays in `placement.test.ts` — all matched, so there was no live drift to
 * fix at the time this fixture was created.
 */

interface PlaceBoardVector {
  name: string;
  itemIds: string[];
  gridSize: number;
  centerType: string;
  chosenCenterId: string | null;
  randomize: boolean;
  seed: number | null;
  expected: (string | null)[];
}

interface Fixture {
  placeBoardVectors: PlaceBoardVector[];
}

const FIXTURE_PATH = path.join(__dirname, 'fixtures/placementVectors.json');
const IOS_COPY_PATH = path.join(
  __dirname,
  '../../../apps/ios/OYBCTests/Fixtures/placementVectors.json',
);
const fixture: Fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));

/** Twin of packages/bingo-core/tests/seededRng.ts, inlined here so a vector's
 * `seed` field alone is enough to reproduce the RNG stream (no cross-file
 * coupling to a specific `makeSeededRng` export needed by the fixture). */
function makeSeededRng(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

describe('placementVectors fixture', () => {
  it('is non-empty', () => {
    expect(fixture.placeBoardVectors.length).toBeGreaterThan(0);
  });
});

describe('placeBoard — cross-platform vectors', () => {
  it.each(fixture.placeBoardVectors.map((v) => [v.name, v] as const))(
    '%s',
    (_name, vector) => {
      const items = vector.itemIds.map((id) => ({ id }));
      const placement = placeBoard({
        items,
        gridSize: vector.gridSize,
        centerType: vector.centerType as CenterSquareType,
        chosenCenterId: vector.chosenCenterId ?? undefined,
        randomize: vector.randomize,
        rng: vector.seed != null ? makeSeededRng(vector.seed) : undefined,
      });
      expect(placement.map((t) => t?.id ?? null)).toEqual(vector.expected);
    },
  );
});

describe('placementVectors iOS bundle copy', () => {
  // Same story as lwwVectors.json / placementResolutionVectors.json —
  // xcodegen can't bundle a resource from outside apps/ios, so
  // apps/ios/OYBCTests/Fixtures/placementVectors.json is a checked-in copy
  // the Swift vector test reads. Run
  // `pnpm --filter @oybc/shared run gen:sync-fixtures` after editing vectors.
  it('is byte-identical to tests/fixtures/placementVectors.json', () => {
    expect(fs.existsSync(IOS_COPY_PATH)).toBe(true);
    const canonical = fs.readFileSync(FIXTURE_PATH, 'utf8');
    const iosCopy = fs.readFileSync(IOS_COPY_PATH, 'utf8');
    expect(iosCopy).toEqual(canonical);
  });
});
