import XCTest
@testable import OYBC

/// Unit tests for `TaskTitle.generateCounterTaskTitle`.
///
/// Parity target: `packages/shared/tests/algorithms/taskTitle.test.ts`.
/// CLAUDE.md calls `generateCounterTaskTitle` "the canonical way to build
/// counting task titles — don't duplicate this logic on either platform";
/// this suite mirrors the TS case list so a divergence between the Swift
/// port and the TypeScript source-of-truth is caught immediately. Extracted
/// from inline title-building in `CreateFormViewModel` (issue #246 part 2).
final class TaskTitleTests: XCTestCase {

    func test_autoGeneratedTitle_whenProvidedTitleAbsent() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(action: "Read", maxCount: 100, unit: "pages"),
            "Read 100 pages"
        )
    }

    func test_autoGeneratedTitle_whenProvidedTitleIsEmptyString() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(action: "Run", maxCount: 5, unit: "miles", providedTitle: ""),
            "Run 5 miles"
        )
    }

    func test_fallsBackToFormula_whenProvidedTitleIsWhitespaceOnly() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(action: "Run", maxCount: 5, unit: "miles", providedTitle: "   "),
            "Run 5 miles"
        )
    }

    func test_returnsProvidedTitle_whenNonBlank() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(
                action: "Read", maxCount: 100, unit: "pages", providedTitle: "My Custom Title"
            ),
            "My Custom Title"
        )
    }

    func test_trimsProvidedTitle_whenReturningIt() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(
                action: "Read", maxCount: 100, unit: "pages", providedTitle: "  Trimmed  "
            ),
            "Trimmed"
        )
    }

    func test_trimsActionAndUnit_withSurroundingWhitespaceInFormula() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(action: "  Walk  ", maxCount: 10, unit: "  km  "),
            "Walk 10 km"
        )
    }

    func test_handlesMaxCountOfOne() {
        XCTAssertEqual(
            TaskTitle.generateCounterTaskTitle(action: "Do", maxCount: 1, unit: "pushup"),
            "Do 1 pushup"
        )
    }

    // Note: the TS suite also asserts `Math.floor` on a fractional `maxCount`
    // (e.g. `5.7 -> 5`). iOS's `maxCount` is `Int` end-to-end (parsed via
    // `Int(...)` at every call site before reaching this helper), so there is
    // no fractional-input case to mirror — the type system enforces it.
}
